networks:
    selenium-net:
        driver : bridge
        
services:
    chrome:
        image: selenium/standalone-chrome:latest
        container_name : chrome
        hostname: chrome
        ports:
          - 4444:4444
          - 7900:7900
        privileged: true
        shm_size: 2g
        networks:
          - selenium-net

    robotframework:
        build: .
        container_name : robotframework
        networks:
          - selenium-net
        depends_on: 
            - chrome
