name: formation_robotframework

networks:
  selenium-net:
    name: selenium-net
    driver: bridge
    
services:
  firefox:
    image: selenium/standalone-firefox:latest
    container_name: firefox
    shm_size: 2gb
    ports:
      - 4444:4444
      - 7900:7900
    networks: 
      - selenium-net
      
  chrome:
    image: selenium/standalone-chrome:latest
    container_name: chrome
    shm_size: 2gb
    ports:
      - 4445:4444
      - 7901:7900
    networks: 
      - selenium-net

  robotframework:
    container_name: robotframework
    build:
      dockerfile: robotframework.Dockerfile
    tty: true
    networks: 
      - selenium-net